from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_TransparencyRenderDLSS():
    g = RenderGraph('TransparencyRenderDLSS')
    g.create_pass('VBufferRT', 'VBufferRT', {'outputSize': 'Default', 'samplePattern': 'Halton', 'sampleCount': 16, 'useAlphaTest': True, 'adjustShadingNormals': True, 'forceCullMode': False, 'cull': 'Back', 'cullNonOpaque': True, 'useTraceRayInline': False, 'useDOF': True})
    g.create_pass('TransparencyRenderer', 'TransparencyRenderer', {})
    g.create_pass('DLSSPass', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.0, 'exposure': 0.0})
    g.create_pass('VideoRecorder', 'VideoRecorder', {})
    g.create_pass('PathBenchmark', 'PathBenchmark', {})
    g.create_pass('ParticlePass', 'ParticlePass', {})
    g.create_pass('ToneMapper', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('TransparencyRenderer0', 'TransparencyRenderer', {})
    g.create_pass('TransparencyRenderer1', 'TransparencyRenderer', {})
    g.create_pass('TransparencyRenderer2', 'TransparencyRenderer', {})
    g.create_pass('DLSSPass0', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.0, 'exposure': 0.0})
    g.create_pass('DLSSPass1', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.0, 'exposure': 0.0})
    g.create_pass('DLSSPass2', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.0, 'exposure': 0.0})
    g.create_pass('ToneMapper0', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('ToneMapper1', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('ToneMapper2', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.add_edge('TransparencyRenderer.outDepth', 'DLSSPass.depth')
    g.add_edge('VBufferRT.vbuffer', 'TransparencyRenderer.vbuffer')
    g.add_edge('TransparencyRenderer.outMotion', 'DLSSPass.mvec')
    g.add_edge('VBufferRT.viewW', 'TransparencyRenderer.viewW')
    g.add_edge('TransparencyRenderer.outColor', 'DLSSPass.color')
    g.add_edge('VBufferRT.mvec', 'TransparencyRenderer.inMotion')
    g.add_edge('VBufferRT.depth', 'TransparencyRenderer.inDepth')
    g.add_edge('VideoRecorder', 'PathBenchmark')
    g.add_edge('PathBenchmark', 'VBufferRT')
    g.add_edge('ParticlePass', 'VideoRecorder')
    g.add_edge('DLSSPass.output', 'ToneMapper.src')
    g.add_edge('VBufferRT.vbuffer', 'TransparencyRenderer0.vbuffer')
    g.add_edge('VBufferRT.depth', 'TransparencyRenderer0.inDepth')
    g.add_edge('VBufferRT.viewW', 'TransparencyRenderer0.viewW')
    g.add_edge('VBufferRT.mvec', 'TransparencyRenderer0.inMotion')
    g.add_edge('VBufferRT.vbuffer', 'TransparencyRenderer1.vbuffer')
    g.add_edge('VBufferRT.depth', 'TransparencyRenderer1.inDepth')
    g.add_edge('VBufferRT.mvec', 'TransparencyRenderer1.inMotion')
    g.add_edge('VBufferRT.viewW', 'TransparencyRenderer1.viewW')
    g.add_edge('VBufferRT.vbuffer', 'TransparencyRenderer2.vbuffer')
    g.add_edge('VBufferRT.depth', 'TransparencyRenderer2.inDepth')
    g.add_edge('VBufferRT.viewW', 'TransparencyRenderer2.viewW')
    g.add_edge('VBufferRT.mvec', 'TransparencyRenderer2.inMotion')
    g.add_edge('TransparencyRenderer0.outColor', 'DLSSPass0.color')
    g.add_edge('TransparencyRenderer0.outDepth', 'DLSSPass0.depth')
    g.add_edge('TransparencyRenderer0.outMotion', 'DLSSPass0.mvec')
    g.add_edge('TransparencyRenderer1.outColor', 'DLSSPass1.color')
    g.add_edge('TransparencyRenderer1.outDepth', 'DLSSPass1.depth')
    g.add_edge('TransparencyRenderer1.outMotion', 'DLSSPass1.mvec')
    g.add_edge('TransparencyRenderer2.outColor', 'DLSSPass2.color')
    g.add_edge('TransparencyRenderer2.outDepth', 'DLSSPass2.depth')
    g.add_edge('TransparencyRenderer2.outMotion', 'DLSSPass2.mvec')
    g.add_edge('DLSSPass0.output', 'ToneMapper0.src')
    g.add_edge('DLSSPass1.output', 'ToneMapper1.src')
    g.add_edge('DLSSPass2.output', 'ToneMapper2.src')
    g.mark_output('ToneMapper.dst')
    g.mark_output('ToneMapper0.dst')
    g.mark_output('ToneMapper1.dst')
    g.mark_output('ToneMapper2.dst')
    return g

TransparencyRenderDLSS = render_graph_TransparencyRenderDLSS()
try: m.addGraph(TransparencyRenderDLSS)
except NameError: None
