from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_TransparencyRenderDLSS():
    g = RenderGraph('TransparencyRenderDLSS')
    g.create_pass('VBufferRT', 'VBufferRT', {'outputSize': 'Default', 'samplePattern': 'Halton', 'sampleCount': 16, 'useAlphaTest': True, 'adjustShadingNormals': True, 'forceCullMode': False, 'cull': 'Back', 'cullNonOpaque': True, 'useTraceRayInline': False, 'useDOF': True})
    g.create_pass('TransparencyRendererAS', 'TransparencyRenderer', {'RenderMode': 'DirectRT+RayReflections', 'ShadowMethod': 'AccelIrregularZ', 'EnableMask': True})
    g.create_pass('DLSSPassAS', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.0, 'exposure': 0.0})
    g.create_pass('VideoRecorder', 'VideoRecorder', {})
    g.create_pass('PathBenchmark', 'PathBenchmark', {})
    g.create_pass('ParticlePass', 'ParticlePass', {})
    g.create_pass('ToneMapperAS', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('TransparencyRendererLL', 'TransparencyRenderer', {'RenderMode': 'DirectRT+RayReflections', 'ShadowMethod': 'LinkedListIrregularZ', 'EnableMask': True})
    g.create_pass('TransparencyRendererRay', 'TransparencyRenderer', {'RenderMode': 'DirectRT+RayReflections', 'ShadowMethod': 'RayTracing', 'EnableMask': False})
    g.create_pass('DLSSPassLL', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.0, 'exposure': 0.0})
    g.create_pass('DLSSPassRay', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.0, 'exposure': 0.0})
    g.create_pass('ToneMapperLL', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('ToneMapperRay', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.add_edge('TransparencyRendererAS.outDepth', 'DLSSPassAS.depth')
    g.add_edge('TransparencyRendererAS.outMotion', 'DLSSPassAS.mvec')
    g.add_edge('TransparencyRendererAS.outColor', 'DLSSPassAS.color')
    g.add_edge('VideoRecorder', 'PathBenchmark')
    g.add_edge('PathBenchmark', 'TransparencyRendererAS')
    g.add_edge('ParticlePass', 'VideoRecorder')
    g.add_edge('DLSSPassAS.output', 'ToneMapperAS.src')
    g.add_edge('TransparencyRendererLL.outColor', 'DLSSPassLL.color')
    g.add_edge('TransparencyRendererLL.outDepth', 'DLSSPassLL.depth')
    g.add_edge('TransparencyRendererLL.outMotion', 'DLSSPassLL.mvec')
    g.add_edge('TransparencyRendererRay.outColor', 'DLSSPassRay.color')
    g.add_edge('TransparencyRendererRay.outDepth', 'DLSSPassRay.depth')
    g.add_edge('TransparencyRendererRay.outMotion', 'DLSSPassRay.mvec')
    g.add_edge('DLSSPassLL.output', 'ToneMapperLL.src')
    g.add_edge('DLSSPassRay.output', 'ToneMapperRay.src')
    g.mark_output('ToneMapperAS.dst')
    g.mark_output('ToneMapperLL.dst')
    g.mark_output('ToneMapperRay.dst')
    return g

TransparencyRenderDLSS = render_graph_TransparencyRenderDLSS()
try: m.addGraph(TransparencyRenderDLSS)
except NameError: None
