from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_TransparencyRenderDLSS():
    g = RenderGraph('TransparencyRenderDLSS')
    g.create_pass('VBufferRT', 'VBufferRT', {'outputSize': 'Default', 'samplePattern': 'Halton', 'sampleCount': 16, 'useAlphaTest': True, 'adjustShadingNormals': True, 'forceCullMode': False, 'cull': 'Back', 'cullNonOpaque': True, 'useTraceRayInline': False, 'useDOF': True})
    g.create_pass('ISDM_AS', 'TransparencyRenderer', {'RenderMode': 'DirectRT+RayReflections', 'ShadowMethod': 'AccelIrregularZ', 'EnableMask': True, 'ShadowResolution': 512})
    g.create_pass('DLSS_IDSM_AS', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.0, 'exposure': 0.0})
    g.create_pass('VideoRecorder', 'VideoRecorder', {})
    g.create_pass('PathBenchmark', 'PathBenchmark', {})
    g.create_pass('ParticlePass', 'ParticlePass', {})
    g.create_pass('ToneMapper_IDSM_AS', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('DSM_AS', 'TransparencyRenderer', {'RenderMode': 'DirectRT+RayReflections', 'ShadowMethod': 'AccelShadow', 'EnableMask': True, 'ShadowResolution': 2048})
    g.create_pass('DSM_LL', 'TransparencyRenderer', {'RenderMode': 'DirectRT+RayReflections', 'ShadowMethod': 'LinkedList', 'EnableMask': True, 'ShadowResolution': 2048})
    g.create_pass('IDSM_LL', 'TransparencyRenderer', {'RenderMode': 'DirectRT+RayReflections', 'ShadowMethod': 'LinkedListIrregularZ', 'EnableMask': True, 'ShadowResolution': 512})
    g.create_pass('DLSS_DSM_AS', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.0, 'exposure': 0.0})
    g.create_pass('DLSS_DSM_LL', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.0, 'exposure': 0.0})
    g.create_pass('DLSS_IDSM_LL', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.0, 'exposure': 0.0})
    g.create_pass('ToneMapper_DSM_AS', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('ToneMapper_DSM_LL', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('ToneMapper_IDSM_LL', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.add_edge('ISDM_AS.outDepth', 'DLSS_IDSM_AS.depth')
    g.add_edge('VBufferRT.vbuffer', 'ISDM_AS.vbuffer')
    g.add_edge('ISDM_AS.outMotion', 'DLSS_IDSM_AS.mvec')
    g.add_edge('VBufferRT.viewW', 'ISDM_AS.viewW')
    g.add_edge('ISDM_AS.outColor', 'DLSS_IDSM_AS.color')
    g.add_edge('VBufferRT.mvec', 'ISDM_AS.inMotion')
    g.add_edge('VBufferRT.depth', 'ISDM_AS.inDepth')
    g.add_edge('VideoRecorder', 'PathBenchmark')
    g.add_edge('PathBenchmark', 'VBufferRT')
    g.add_edge('ParticlePass', 'VideoRecorder')
    g.add_edge('DLSS_IDSM_AS.output', 'ToneMapper_IDSM_AS.src')
    g.add_edge('VBufferRT.vbuffer', 'DSM_AS.vbuffer')
    g.add_edge('VBufferRT.depth', 'DSM_AS.inDepth')
    g.add_edge('VBufferRT.viewW', 'DSM_AS.viewW')
    g.add_edge('VBufferRT.mvec', 'DSM_AS.inMotion')
    g.add_edge('VBufferRT.vbuffer', 'DSM_LL.vbuffer')
    g.add_edge('VBufferRT.depth', 'DSM_LL.inDepth')
    g.add_edge('VBufferRT.mvec', 'DSM_LL.inMotion')
    g.add_edge('VBufferRT.viewW', 'DSM_LL.viewW')
    g.add_edge('VBufferRT.vbuffer', 'IDSM_LL.vbuffer')
    g.add_edge('VBufferRT.depth', 'IDSM_LL.inDepth')
    g.add_edge('VBufferRT.viewW', 'IDSM_LL.viewW')
    g.add_edge('VBufferRT.mvec', 'IDSM_LL.inMotion')
    g.add_edge('DSM_AS.outColor', 'DLSS_DSM_AS.color')
    g.add_edge('DSM_AS.outDepth', 'DLSS_DSM_AS.depth')
    g.add_edge('DSM_AS.outMotion', 'DLSS_DSM_AS.mvec')
    g.add_edge('DSM_LL.outColor', 'DLSS_DSM_LL.color')
    g.add_edge('DSM_LL.outDepth', 'DLSS_DSM_LL.depth')
    g.add_edge('DSM_LL.outMotion', 'DLSS_DSM_LL.mvec')
    g.add_edge('IDSM_LL.outColor', 'DLSS_IDSM_LL.color')
    g.add_edge('IDSM_LL.outDepth', 'DLSS_IDSM_LL.depth')
    g.add_edge('IDSM_LL.outMotion', 'DLSS_IDSM_LL.mvec')
    g.add_edge('DLSS_DSM_AS.output', 'ToneMapper_DSM_AS.src')
    g.add_edge('DLSS_DSM_LL.output', 'ToneMapper_DSM_LL.src')
    g.add_edge('DLSS_IDSM_LL.output', 'ToneMapper_IDSM_LL.src')
    g.mark_output('ToneMapper_IDSM_AS.dst')
    g.mark_output('ToneMapper_DSM_AS.dst')
    g.mark_output('ToneMapper_DSM_LL.dst')
    g.mark_output('ToneMapper_IDSM_LL.dst')
    return g

TransparencyRenderDLSS = render_graph_TransparencyRenderDLSS()
try: m.addGraph(TransparencyRenderDLSS)
except NameError: None
